### ISSUE TITLE
no discord.js 

### ISSUE THREAD

**Issue by haris69420** [schnappi21/nekos.life-discord-bot#17]
my error is

Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\HP\Downloads\kkjhj\index.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:804:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1028:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> ←[90m(C:\Users\HP\Downloads\kkjhj\←[39mindex.js:1:17←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1126:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1004:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:839:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\HP\\Downloads\\kkjhj\\index.js'←[39m ]
}
Press any key to continue . . .

**Comment by Zaxbys** [comment]
have you tried `npm install discord.js`?
